version: '3'
services:
  frontend:
    build: ./frontend
    image: registry.gitlab.com/patrickrb/badgepirates.com
    ports:
      - "80:80"
  mongo:
    image: mongo:3.6

  backend:
    build: ./backend
    image: registry.gitlab.com/patrickrb/badgepirates-backend
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test
     - SENDGRID_KEY=${SENDGRID_KEY}
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/starter
     - /starter/node_modules
